name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: terraform-github-repository
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pre-commit
        run: make test/docker/pre-commit

  validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    strategy:
      matrix:
        dir: [., test/unit-complete]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init & Validate
        working-directory: ${{ matrix.dir }}
        run: |
          terraform init -backend=false
          terraform validate

  unit-tests:
    needs: pre-commit
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for Terraform file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            terraform:
              - '**/*.tf'
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'

      - name: Run Unit Tests
        if: steps.changes.outputs.terraform == 'true'
        run: make test/docker/unit-tests
        env:
          GITHUB_OWNER: ${{ secrets.TEST_GITHUB_ORGANIZATION }}
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
